###############################################
# Moved: archived under
# private-projects/mongo-backup-v2/archive/pre-unified/Dockerfile.mongo-backup
###############################################
FROM scratch
