# =============================================================================
# Docker Compose - Node.js App (Standalone for Dokploy)
# =============================================================================
# Deploy this stack after the MongoDB stack. The app connects to MongoDB using
# DATABASE_URL which should reference the 'mongo' host on the shared network.
#
# Example DATABASE_URL in Dokploy envs:
#   mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_APP_DB}?authSource=${MONGO_AUTH_SOURCE:-admin}
# =============================================================================

name: ${APP_NAME:-lynx-portfolio-back}-app

services:
  app:
    build:
      context: .
      target: production
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        NODE_ENV: production
    image: ${APP_NAME:-lynx-portfolio-back}-app:latest
    container_name: ${APP_NAME:-lynx-portfolio-back}-app
    hostname: ${APP_NAME:-lynx-portfolio-back}-app
    # Expose the app port for direct access if needed; nginx will proxy to this
    ports:
      - "${PROD_PORT:-6165}:6165"
    environment:
      NODE_ENV: production
      # Keep app at 6165 to match nginx.conf upstream
      PORT: 6165
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret}
      DATABASE_URL: ${DATABASE_URL}
      MONGO_APP_DB: ${MONGO_APP_DB:-lynx_portfolio}
      MONGO_APP_USER: ${MONGO_APP_USER:-portfolio}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD:-portfolio_pass}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE:-admin}
    volumes:
      - node_logs:/app/logs
      - node_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PROD_PORT:-6165}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  default:
    external: true
    name: ${APP_NAME:-lynx-portfolio-back}-network

volumes:
  node_logs:
    name: ${APP_NAME:-lynx-portfolio-back}-logs
    driver: local
  node_uploads:
    name: ${APP_NAME:-lynx-portfolio-back}-uploads
    driver: local
