# =============================================================================
# Docker Compose - Combined Production (Node + Nginx) for Dokploy
# =============================================================================
# This deploys a single container built from the Dockerfile production-nginx
# stage. Use this when you prefer a single service (no separate nginx).
# =============================================================================

name: lynx-portfolio-back-prod-nginx

services:
  prod-nginx:
    build:
      context: .
      target: production-nginx
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        NODE_ENV: production
    image: lynx-portfolio-back-prod-nginx:latest
    container_name: lynx-portfolio-back-prod-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://localhost:${PROD_PORT:-6165}}
      NODE_ENV: production
      PORT: ${PROD_PORT:-6165}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret}
      MONGO_URI: ${MONGO_URI}
      MONGO_APP_DB: ${MONGO_APP_DB:-lynx_portfolio}
      MONGO_APP_TEST_DB: ${MONGO_APP_TEST_DB:-lynx_portfolio_test}
      MONGO_APP_USER: ${MONGO_APP_USER:-database_user}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD:-portfolio_pass}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE:-admin}
      REDIS_URL: ${REDIS_URL:-}
      NGINX_HOST: ${NGINX_HOST:-localhost}
      NGINX_PORT: ${NGINX_PORT:-80}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - node_logs:/app/logs
      - nginx_logs:/var/log/nginx
      - supervisor_logs:/var/log/supervisor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  default:
    external: true
    name: lynx-portfolio-back-network

volumes:
  node_logs:
    name: lynx-portfolio-back-logs
    driver: local
  nginx_logs:
    name: lynx-portfolio-back-nginx-logs
    driver: local
  supervisor_logs:
    name: lynx-portfolio-back-supervisor-logs
    driver: local
